// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"time"

	"github.com/google/uuid"
)

type Application struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	ExternalID     string    `json:"external_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Version        int32     `json:"version"`
}

type Organization struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	ExternalID string    `json:"external_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	Version    int32     `json:"version"`
}

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	GivenName    *string   `json:"given_name"`
	FamilyName   *string   `json:"family_name"`
	PrimaryEmail *string   `json:"primary_email"`
	AvatarUrl    *string   `json:"avatar_url"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Version      int32     `json:"version"`
}

type UserAuth struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	Value         string    `json:"value"`
	Provider      string    `json:"provider"`
	ProviderID    string    `json:"provider_id"`
	ProviderData  []byte    `json:"provider_data"`
	Email         *string   `json:"email"`
	EmailVerified bool      `json:"email_verified"`
	PrimaryAuth   bool      `json:"primary_auth"`
	Active        bool      `json:"active"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Version       int32     `json:"version"`
}

type UserInvite struct {
	ID        uuid.UUID `json:"id"`
	LinkID    uuid.UUID `json:"link_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Version   int32     `json:"version"`
}

type UserSession struct {
	ID             uuid.UUID  `json:"id"`
	UserID         uuid.UUID  `json:"user_id"`
	ImpersonatorID *uuid.UUID `json:"impersonator_id"`
	Token          string     `json:"token"`
	ExpiresAt      time.Time  `json:"expires_at"`
	UserExpired    bool       `json:"user_expired"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	Version        int32      `json:"version"`
}
