// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAuth(ctx context.Context, arg CreateUserAuthParams) (UserAuth, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error)
	ExpireUserSession(ctx context.Context, id uuid.UUID) error
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (GetUserByProviderIDRow, error)
	GetUserBySessionToken(ctx context.Context, token string) (GetUserBySessionTokenRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
